<!DOCTYPE html>
    <html lang="en">
        <head>
            <title>
                Crystals, Charms, and Coffee
            </title>
            <meta charset="utf-8">
            <link rel="stylesheet" href="final.css">
        </head>
    </html>
<body>
<form name="login" action="login.php" method="POST">
    <div class="login">
        <label for="username">User Name</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="text" name="password">
        <input type="submit" value="Log in">

    </div>
</form>

